import BXC from '../images/BXC.svg';
import G2H from '../images/G2H.svg';
import GHN from '../images/GHN.svg';
import TDA from '../images/TDA.svg';

export const Cards = [
    {
        name: 'Вытяжное устройство BXC',
        name_big: 'BXC',
        description: 'Вытяжное устройство для механической системы вентиляции',
        image: BXC,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '1',
    },
    {
        name: 'Вытяжное устройство G2H',
        name_big: 'G2H',
        description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        image: G2H,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '2',
    },
    {
        name: 'Вытяжное устройство GHN',
        name_big: 'GHN',
        description: 'Вытяжное устройство с датчиком присутствия',
        image: GHN,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '3',
    },
    {
        name: 'Вытяжное устройство TDA',
        name_big: 'TDA',
        description: 'Вытяжное устройство с датчиком присутствия',
        image: TDA,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '4',
    },
    {
        name: 'Вытяжное устройство BXC',
        name_big: 'BXC',
        description: 'Вытяжное устройство для механической системы вентиляции',
        image: BXC,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '1',
    },
    {
        name: 'Вытяжное устройство G2H',
        name_big: 'G2H',
        description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
        image: G2H,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '2',
    },
    {
        name: 'Вытяжное устройство GHN',
        name_big: 'GHN',
        description: 'Вытяжное устройство с датчиком присутствия',
        image: GHN,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '3',
    },
    {
        name: 'Вытяжное устройство TDA',
        name_big: 'TDA',
        description: 'Вытяжное устройство с датчиком присутствия',
        image: TDA,
        property: '12-72/168 м3/ч / гидрорегулируемый расход / от датчика присутствия',
        article: 'Артикул: G2H1065',
        price: '12644',
        priceBig: '12 644 ₽',
        price_unit: '12 644 ₽/шт.',
        price_eur: '143.30 €',
        id: '4',
    },
];